실습과제 2강

1. pandas 라이브러리를 사용하여 usa_housing.csv 파일을 불러오세요.
2. Bedrooms 변수의 값이 3 이상인 데이터만 필터링하여 새로운 데이터프레임으로 저장하세요.
3. 입력 데이터인 CrimeRate 변수와 타깃(정답) 데이터인 Price 변수를 각각 2차원 배열 형태로 추출하세요.
4. train_test_split 함수를 사용하여 전체 데이터를 훈련 세트 60%, 검증 세트 20%, 테스트 세트 20%의 비율로 분할하세요. 이때 random_state 값은 42로 고정하세요.
5. 분할이 완료된 후 각 데이터 세트의 샘플 개수를 print() 함수로 출력하여 정상적으로 분할되었는지 확인하세요.

**출력 및 검증 방법**
훈련 세트, 검증 세, 테스트 세트의 데이터 개수가 각각 명확한 숫자로 출력되는지 확인하세요. 각 데이터 개수가 출력된 부분을 캡처하여 작성한 코드와 함께 제출하세요.

In [24]:
import pandas as pd

df = pd.read_csv('usa_housing.csv')
df.head()

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
0,221958,1,1.9,4827,1979,2,1.45,82240,48.60,5
1,771155,2,2.0,1035,1987,2,1.75,74315,92.03,9
2,231932,1,3.0,2769,1982,1,1.46,79249,52.08,3
3,465838,3,3.3,2708,1907,3,1.62,80587,61.65,1
4,359178,4,3.4,1175,1994,2,0.74,20756,15.66,4

In [25]:
large_room=df[df['Bedrooms']>=3]
large_room

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
3,465838,3,3.3,2708,1907,3,1.62,80587,61.65,1
4,359178,4,3.4,1175,1994,2,0.74,20756,15.66,4
9,737147,3,2.6,4191,2017,0,1.65,66549,37.60,3
10,621430,4,2.3,3765,1979,2,0.96,44503,55.01,9
13,275203,4,1.4,1672,1924,1,1.49,84069,27.38,2
...,...,...,...,...,...,...,...,...,...,...
294,851102,4,3.3,3804,2006,1,0.26,95667,72.52,3
295,862002,4,2.8,1129,1944,0,1.80,35227,32.30,3
296,242483,3,2.4,4440,1988,2,0.46,15978,99.71,9
298,314835,5,2.0,4907,1941,3,0.53,27153,65.61,8
299,501896,5,3.8,2141,1999,0,0.77,69765,12.98,9

In [26]:
X = large_room[['CrimeRate']]
y = large_room['Price']

X.shape, y.shape

((174, 1), (174,))

In [27]:
from sklearn.model_selection import train_test_split # Train set, Validation Set, Test Set 분리

X_train_tmp, X_test, y_train_tmp, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_valid, y_train, y_valid = train_test_split(X_train_tmp, y_train_tmp, test_size=0.25, random_state=42)



print("훈련 세트",len(X_train))
print("테스트 세트",len(X_test))
print("검증 세트", len(X_valid))

훈련 세트 104
테스트 세트 35
검증 세트 35

2.

1. scikit-learn 라이브러리에서 제공하는 StandardScaler를 불러오세요.
2. 입력 데이터용 스케일러와 타깃 데이터용 스케일러를 각각 독립적으로 생성하세요.
3. fit_transform() 함수를 사용하여 앞서 분할한 데이터들을 표준 점수로 변환하세요.
4. 변환이 끝난 후, 후속 연산의 편의를 위해 flatten() 함수를 사용하여 데이터를 1차원 배열 형태로 변환하세요.
5. 변환된 데이터의 첫 번째 값과 전체 크기(shape)를 print() 함수를 통해 화면에 출력하세요.

**출력 및 검증 방법**
출력창에 표준화된 첫 번째 데이터 값과 전체 데이터의 크기가 정상적으로 표시되는지 확인하세요. 해당 출력 결과가 담긴 화면을 캡처하여 작성된 코드와 함께 제출하세요.

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
X_Scaled = StandardScaler().fit_transform(X)
X_Scaled

array([[ 0.39643667],
       [-1.18126208],
       [-0.42860475],
       [ 0.16864977],
       [-0.77920447],
       [ 1.46607458],
       [ 1.68597127],
       [ 0.58511558],
       [-0.63134882],
       [ 1.29797882],
       [ 0.46367498],
       [-0.95999318],
       [ 1.63794391],
       [ 0.8482369 ],
       [-1.09892947],
       [-1.53357707],
       [ 0.86538953],
       [-0.79464184],
       [ 0.13262925],
       [-1.34832868],
       [-1.40321709],
       [-0.54387041],
       [-0.30030309],
       [ 0.83177038],
       [-1.35518973],
       [-1.3966991 ],
       [ 0.26161701],
       [ 1.29043166],
       [ 0.19575092],
       [ 1.06641834],
       [ 0.82593849],
       [ 1.30552598],
       [-0.76513932],
       [-1.05296042],
       [ 1.29969408],
       [-0.65193197],
       [ 1.07773907],
       [ 0.64137621],
       [-0.43100612],
       [ 0.12954178],
       [ 0.07979915],
       [ 1.19060337],
       [ 1.16315916],
       [ 0.85269659],
       [ 0.88425742],
       [ 0.60878621],
       [ 0.87602416],
       [ 1.17002021],
       [-0.10510618],
       [-1.29069585],
       [-0.39635781],
       [ 0.95869983],
       [-0.97337223],
       [-1.24575597],
       [-1.7119644 ],
       [-1.10647662],
       [-1.61865411],
       [-1.0965281 ],
       [ 0.76315987],
       [ 0.69283409],
       [ 0.46504719],
       [-1.20733408],
       [ 1.65029381],
       [ 0.0664201 ],
       [-0.43718107],
       [-0.9092214 ],
       [-0.44438517],
       [-1.50407455],
       [ 0.91135858],
       [ 0.79815123],
       [-0.69138302],
       [-0.01625557],
       [ 1.68151159],
       [-1.02242874],
       [ 1.64206054],
       [-1.15141651],
       [ 0.68391472],
       [ 0.2935209 ],
       [ 0.67499536],
       [ 1.47053426],
       [ 0.96624699],
       [-1.52602991],
       [ 1.20672684],
       [-0.94489886],
       [-0.42551728],
       [-0.1346087 ],
       [-0.06874261],
       [-0.22551763],
       [ 0.70346872],
       [-1.54764222],
       [ 1.40123764],
       [ 0.95801372],
       [-0.94592802],
       [-0.35038877],
       [-0.09893123],
       [-1.67251336],
       [ 1.62559402],
       [-0.44507127],
       [ 1.17962568],
       [-0.79875847],
       [-1.18194819],
       [ 1.20809905],
       [-1.55896296],
       [ 0.20947302],
       [-0.53186357],
       [ 0.92954036],
       [-1.42208499],
       [-0.90613392],
       [ 0.16247482],
       [-1.27937512],
       [ 1.30758429],
       [ 0.98374267],
       [ 0.42353783],
       [ 1.64206054],
       [-1.0625659 ],
       [-0.55793557],
       [ 1.53022541],
       [-1.64301084],
       [-1.41385172],
       [ 0.62731105],
       [ 0.15149714],
       [-0.33255003],
       [ 0.14257777],
       [ 0.99746477],
       [ 0.16419008],
       [-0.94284055],
       [ 1.18682979],
       [ 0.56007275],
       [-0.97714581],
       [-1.3836631 ],
       [ 1.23863072],
       [-0.13975449],
       [ 0.85201048],
       [-0.49721526],
       [ 1.63691476],
       [ 1.00535498],
       [-0.01248199],
       [-0.55278978],
       [ 0.15046798],
       [ 0.88322827],
       [-1.65707599],
       [-1.16410945],
       [ 0.19575092],
       [-1.39532689],
       [-0.74970195],
       [ 1.02010624],
       [-0.44266991],
       [-0.16891396],
       [-0.3551915 ],
       [-0.20527753],
       [-1.04747158],
       [-1.39601299],
       [ 0.88014079],
       [-0.64712924],
       [-1.04678548],
       [ 1.35869912],
       [ 0.19506482],
       [-1.14901514],
       [-0.47285853],
       [-1.13906662],
       [-0.47080022],
       [ 1.09592086],
       [-0.64404176],
       [ 1.0211354 ],
       [ 1.22113504],
       [-1.31505258],
       [ 0.81907744],
       [ 1.67224917],
       [-0.05330524],
       [ 0.76933481],
       [-0.61042261],
       [ 1.70209474],
       [ 0.53228549],
       [-1.27320017]])

In [30]:
flat_X = X_Scaled.flatten()

print(flat_X[0], flat_X.shape)

0.39643667256090737 (174,)

학습률이 너무 크면 비용 함수(Loss Function)의 최솟값을 지나쳐 발산할 수 있고, 너무 작으면 최적화에 과도한 시간이 소요될 수 있습니다. 학습률을 0.05로 설정하고 가중치와 편향의 초기값을 0으로 세팅하여, 모델이 안정적으로 수렴할 수 있도록 기반 코드를 작성합니다.

<aside>

**요구사항**

---

1. 모델의 파라미터인 가중치와 편향의 초기값을 모두 0.0으로 설정하세요.
2. 하이퍼파라미터인 학습률을 0.05로 설정하세요.
3. 총 학습 횟수인 에포크(Epoch)를 150회로 지정하세요.
4. 훈련 과정과 검증 과정에서 발생하는 손실(Loss)의 변화를 기록할 수 있도록 빈 리스트 train_losses와 valid_losses를 각각 생성하세요.
5. 설정된 초기 가중치, 학습률, 그리고 생성된 리스트 변수들을 print() 함수로 출력하여 변수가 정상적으로 정의되었는지 확인하세요.

**출력 및 검증 방법**
초기 가중치 값 0.0과 설정한 학습률 0.05, 그리고 리스트의 값들이 에러 없이 정상적으로 출력되는지 확인하세요. 출력 전체 화면을 캡처하여 작성된 코드와 함께 제출하세요.

</aside>

In [35]:
weight = 0.0          # 가중치(w): 집 크기에 따른 가격 영향력 (초기값 0)
bias = 0.0            # 편향(b): 기본적으로 깔고 가는 베이스 집값 (초기값 0)
learning_rate = 0.05   # 보폭(학습률): 스케일링을 했으므로 보폭을 조금 넓게 잡아도 안전합니다!
epochs = 150          # 훈련 횟수: 산을 내려가는 걸음을 총 200번 반복합니다.

# 훈련 과정에서 오차가 어떻게 줄어드는지 기록할 빈 리스트(수첩)를 만듭니다.
train_losses = []
valid_losses = []
history_w = []

N_train = len(X_train)
N_valid = len(X_valid)

In [41]:
y_train

165    219176
81     559773
124    803550
154    591234
208    668550
        ...
111    532315
277    206081
50     373538
157    572525
130    686146
Name: Price, Length: 104, dtype: int64

In [50]:
import numpy as np
# 경사하강법 루프 시작 (200번 반복)
for epoch in range(epochs):
    # 훈련 세트: 현재 가중치로 집값을 예측해 봅니다 (y_pred = w * x + b)
    y_pred_train = weight * X_train + bias
    # 예측 집값과 실제 집값 차이의 제곱 평균(MSE Loss)을 구합니다.
    train_loss = np.mean((y_pred_train - y_train) ** 2)
    train_losses.append(train_loss)
    
    # 검증 세트: 모의고사 데이터를 넣어 현재 실력을 중간 점검합니다.
    y_pred_valid = weight * X_valid + bias
    valid_loss = np.mean((y_pred_valid - y_valid) ** 2)
    valid_losses.append(valid_loss)
    history_w.append(weight)
    
    # 기울기(Gradient) 구하기: 어느 방향으로 가야 오차가 줄어들지 미분 공식으로 찾습니다.
    dw = (2 / N_train) * np.sum((y_pred_train - y_train) * X_train)
    db = (2 / N_train) * np.sum(y_pred_train - y_train)
    
    # 한 걸음 이동! (현재 위치 - 보폭 * 기울기)
    print("y_train:", dw)
    weight -= learning_rate * dw
    bias -= learning_rate * db

y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0
y_train: 0.0

In [39]:
print(weight, learning_rate)
history_w

0.0 0.05

[0.0,
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0)]

In [59]:
df = pd.read_csv('usa_housing.csv')

X_sqft = df['SquareFeet'].values.reshape(-1,1)
y_price = df['Price'].values
X_sqft.shape,y_price.shape

((300, 1), (300,))

In [60]:
df = df[df['Bedrooms'] >= 3]
df.head()

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
3,465838,3,3.3,2708,1907,3,1.62,80587,61.65,1
4,359178,4,3.4,1175,1994,2,0.74,20756,15.66,4
9,737147,3,2.6,4191,2017,0,1.65,66549,37.60,3
10,621430,4,2.3,3765,1979,2,0.96,44503,55.01,9
13,275203,4,1.4,1672,1924,1,1.49,84069,27.38,2

In [61]:
X_sqft = df['CrimeRate'].values.reshape(-1,1)
y_price = df['Price'].values
X_sqft.shape,y_price.shape

((174, 1), (174,))

In [62]:
ss = StandardScaler()
#ss.fit(X_sqft)
#X_scaled = ss.transform(X_sqft)
X_scaled = ss.fit_transform(X_sqft).flatten()  # 2차원 배열  -> 1차원 배열

X_scaled

array([ 0.39643667, -1.18126208, -0.42860475,  0.16864977, -0.77920447,
        1.46607458,  1.68597127,  0.58511558, -0.63134882,  1.29797882,
        0.46367498, -0.95999318,  1.63794391,  0.8482369 , -1.09892947,
       -1.53357707,  0.86538953, -0.79464184,  0.13262925, -1.34832868,
       -1.40321709, -0.54387041, -0.30030309,  0.83177038, -1.35518973,
       -1.3966991 ,  0.26161701,  1.29043166,  0.19575092,  1.06641834,
        0.82593849,  1.30552598, -0.76513932, -1.05296042,  1.29969408,
       -0.65193197,  1.07773907,  0.64137621, -0.43100612,  0.12954178,
        0.07979915,  1.19060337,  1.16315916,  0.85269659,  0.88425742,
        0.60878621,  0.87602416,  1.17002021, -0.10510618, -1.29069585,
       -0.39635781,  0.95869983, -0.97337223, -1.24575597, -1.7119644 ,
       -1.10647662, -1.61865411, -1.0965281 ,  0.76315987,  0.69283409,
        0.46504719, -1.20733408,  1.65029381,  0.0664201 , -0.43718107,
       -0.9092214 , -0.44438517, -1.50407455,  0.91135858,  0.79815123,
       -0.69138302, -0.01625557,  1.68151159, -1.02242874,  1.64206054,
       -1.15141651,  0.68391472,  0.2935209 ,  0.67499536,  1.47053426,
        0.96624699, -1.52602991,  1.20672684, -0.94489886, -0.42551728,
       -0.1346087 , -0.06874261, -0.22551763,  0.70346872, -1.54764222,
        1.40123764,  0.95801372, -0.94592802, -0.35038877, -0.09893123,
       -1.67251336,  1.62559402, -0.44507127,  1.17962568, -0.79875847,
       -1.18194819,  1.20809905, -1.55896296,  0.20947302, -0.53186357,
        0.92954036, -1.42208499, -0.90613392,  0.16247482, -1.27937512,
        1.30758429,  0.98374267,  0.42353783,  1.64206054, -1.0625659 ,
       -0.55793557,  1.53022541, -1.64301084, -1.41385172,  0.62731105,
        0.15149714, -0.33255003,  0.14257777,  0.99746477,  0.16419008,
       -0.94284055,  1.18682979,  0.56007275, -0.97714581, -1.3836631 ,
        1.23863072, -0.13975449,  0.85201048, -0.49721526,  1.63691476,
        1.00535498, -0.01248199, -0.55278978,  0.15046798,  0.88322827,
       -1.65707599, -1.16410945,  0.19575092, -1.39532689, -0.74970195,
        1.02010624, -0.44266991, -0.16891396, -0.3551915 , -0.20527753,
       -1.04747158, -1.39601299,  0.88014079, -0.64712924, -1.04678548,
        1.35869912,  0.19506482, -1.14901514, -0.47285853, -1.13906662,
       -0.47080022,  1.09592086, -0.64404176,  1.0211354 ,  1.22113504,
       -1.31505258,  0.81907744,  1.67224917, -0.05330524,  0.76933481,
       -0.61042261,  1.70209474,  0.53228549, -1.27320017])

In [63]:
# 1차 분할 - 테스트 세트 (20%)
X_train_tmp, X_test, y_train_tmp, y_test = train_test_split(
    X_scaled, y_price, test_size=0.2, random_state=42
)

#2차 분할 = 검증 세트 (20%)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_tmp, y_train_tmp, test_size=0.2, random_state=42
)

print("전체:", X_scaled)
print(X_valid.shape)

전체: [ 0.39643667 -1.18126208 -0.42860475  0.16864977 -0.77920447  1.46607458
  1.68597127  0.58511558 -0.63134882  1.29797882  0.46367498 -0.95999318
  1.63794391  0.8482369  -1.09892947 -1.53357707  0.86538953 -0.79464184
  0.13262925 -1.34832868 -1.40321709 -0.54387041 -0.30030309  0.83177038
 -1.35518973 -1.3966991   0.26161701  1.29043166  0.19575092  1.06641834
  0.82593849  1.30552598 -0.76513932 -1.05296042  1.29969408 -0.65193197
  1.07773907  0.64137621 -0.43100612  0.12954178  0.07979915  1.19060337
  1.16315916  0.85269659  0.88425742  0.60878621  0.87602416  1.17002021
 -0.10510618 -1.29069585 -0.39635781  0.95869983 -0.97337223 -1.24575597
 -1.7119644  -1.10647662 -1.61865411 -1.0965281   0.76315987  0.69283409
  0.46504719 -1.20733408  1.65029381  0.0664201  -0.43718107 -0.9092214
 -0.44438517 -1.50407455  0.91135858  0.79815123 -0.69138302 -0.01625557
  1.68151159 -1.02242874  1.64206054 -1.15141651  0.68391472  0.2935209
  0.67499536  1.47053426  0.96624699 -1.52602991  1.20672684 -0.94489886
 -0.42551728 -0.1346087  -0.06874261 -0.22551763  0.70346872 -1.54764222
  1.40123764  0.95801372 -0.94592802 -0.35038877 -0.09893123 -1.67251336
  1.62559402 -0.44507127  1.17962568 -0.79875847 -1.18194819  1.20809905
 -1.55896296  0.20947302 -0.53186357  0.92954036 -1.42208499 -0.90613392
  0.16247482 -1.27937512  1.30758429  0.98374267  0.42353783  1.64206054
 -1.0625659  -0.55793557  1.53022541 -1.64301084 -1.41385172  0.62731105
  0.15149714 -0.33255003  0.14257777  0.99746477  0.16419008 -0.94284055
  1.18682979  0.56007275 -0.97714581 -1.3836631   1.23863072 -0.13975449
  0.85201048 -0.49721526  1.63691476  1.00535498 -0.01248199 -0.55278978
  0.15046798  0.88322827 -1.65707599 -1.16410945  0.19575092 -1.39532689
 -0.74970195  1.02010624 -0.44266991 -0.16891396 -0.3551915  -0.20527753
 -1.04747158 -1.39601299  0.88014079 -0.64712924 -1.04678548  1.35869912
  0.19506482 -1.14901514 -0.47285853 -1.13906662 -0.47080022  1.09592086
 -0.64404176  1.0211354   1.22113504 -1.31505258  0.81907744  1.67224917
 -0.05330524  0.76933481 -0.61042261  1.70209474  0.53228549 -1.27320017]
(28,)

In [65]:
weight = 0.0          # 가중치(w): 집 크기에 따른 가격 영향력 (초기값 0)
bias = 0.0            # 편향(b): 기본적으로 깔고 가는 베이스 집값 (초기값 0)
learning_rate = 0.05   # 보폭(학습률): 스케일링을 했으므로 보폭을 조금 넓게 잡아도 안전합니다!
epochs = 150          # 훈련 횟수: 산을 내려가는 걸음을 총 200번 반복합니다.

# 훈련 과정에서 오차가 어떻게 줄어드는지 기록할 빈 리스트(수첩)를 만듭니다.
train_losses = []
valid_losses = []
history_w = []

N_train = len(X_train)
N_valid = len(X_valid)

import numpy as np
# 경사하강법 루프 시작 (200번 반복)
for epoch in range(epochs):
    # 훈련 세트: 현재 가중치로 집값을 예측해 봅니다 (y_pred = w * x + b)
    y_pred_train = weight * X_train + bias
    # 예측 집값과 실제 집값 차이의 제곱 평균(MSE Loss)을 구합니다.
    train_loss = np.mean((y_pred_train - y_train) ** 2)
    train_losses.append(train_loss)
    
    # 검증 세트: 모의고사 데이터를 넣어 현재 실력을 중간 점검합니다.
    y_pred_valid = weight * X_valid + bias
    valid_loss = np.mean((y_pred_valid - y_valid) ** 2)
    valid_losses.append(valid_loss)
    history_w.append(weight)
    
    # 기울기(Gradient) 구하기: 어느 방향으로 가야 오차가 줄어들지 미분 공식으로 찾습니다.
    dw = (2 / N_train) * np.sum((y_pred_train - y_train) * X_train)
    db = (2 / N_train) * np.sum(y_pred_train - y_train)
    
    # 한 걸음 이동! (현재 위치 - 보폭 * 기울기)
    weight -= learning_rate * dw
    bias -= learning_rate * db

In [66]:
print(weight)

-18445.438880464244